########################################################################
# 7. Pi-hat / Wi-Fi / Tiny-Display side-car
# /docker/touch-display/docker-compose.display-hat.yaml
########################################################################
display-agent:
  build:                       # reuse the Dockerfile you pasted
    context: docker/touch-display
  image: cdaprod/display-agent:${IMAGE_TAG:-dev}
  container_name: thatdamtoolbox-display-agent
  <<: [*common-config, *standard-logging, *network-host]
  privileged: true             # needs /dev/i2c-1 and iw*
  devices:
    - /dev/i2c-1
  device_cgroup_rules:
    - "c 89:* rmw"             # I2C major number
  environment:
    API_BASE:   "http://127.0.0.1:8080"
    DEVICE_ID:  "${HOSTNAME:-pi-hat}"
    ESP32_ADDR: "0x08"
    # …anything else wifi_manager.py expects
  healthcheck:
    <<: *healthcheck-defaults
    test: ["CMD-SHELL", "curl -sf http://localhost:8080/api/status || exit 1"]