name: thatdamtoolbox-web-site-dev

services:
  web-site:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: thatdamtoolbox-web-site-dev
    restart: unless-stopped
    ports: ["3000:3000"]
    environment:
      NODE_ENV: development
    env_file:
      - ./.env
    volumes:
      - ./:/app
      - /app/node_modules
    networks: [damnet]

networks:
  damnet:
    external: true