services:
  # ────────────────────────────────────────────────────────────────────────────
  # A) DEFAULT: SAFE DISCOVERY (no docker.sock, no privileged)
  # ────────────────────────────────────────────────────────────────────────────
  thatdamtoolbox-discovery:
    build:
      context: ../../../
      dockerfile: host/services/discovery/Dockerfile
    image: cdaprod/thatdam-discovery:${IMAGE_TAG:-dev}
    container_name: thatdamtoolbox-discovery
    network_mode: host
    restart: unless-stopped
    environment:
      ROLE: agent
      UPSTREAM_HOST: api-gateway
      UPSTREAM_PORT: "8080"
      DISCOVERY_BACKEND: ${DISCOVERY_BACKEND:-auto}     # auto|mdns|serf
      SERVICE_NAME: ${SERVICE_NAME:-thatdam}
      SERVICE_PORT: ${SERVICE_PORT:-8080}
      DISCOVERY_HTTP_PORT: ${DISCOVERY_HTTP_PORT:-9999}
      LEADER_FILE: ${LEADER_FILE:-/run/discovery/leader.env}
      LOG_FORMAT: text
      DISCOVERY_ORCHESTRATE: "false"
    volumes:
      - discovery-run:/run/discovery
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:9999/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # ────────────────────────────────────────────────────────────────────────────
  # B) OPTIONAL: ORCHESTRATOR PROFILE (off by default)
  # ────────────────────────────────────────────────────────────────────────────
  thatdamtoolbox-discovery-orchestrator:
    extends:
      service: thatdamtoolbox-discovery
    container_name: thatdamtoolbox-discovery-orchestrator
    profiles: ["orchestrator"]
    environment:
      DISCOVERY_ORCHESTRATE: "true"
      LOG_FORMAT: text
    volumes:
      - discovery-run:/run/discovery
      - /var/run/docker.sock:/var/run/docker.sock:rw