services:
  rabbitmq:
    build:
      context: ./docker/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: video
      RABBITMQ_DEFAULT_PASS: video
    ports:
      - "5672:5672"
      - "15672:15672"
      - "9419:9419"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-logs:/var/log/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
