version: "3.9"
services:
  thatdam-run:
    image: ${EDGE_IMG_CHANNEL:?missing}
    env_file:
      - ./.env.dev
    environment:
      FEATURE_FLAGS: "${FEATURE_FLAGS:-dev,debug}"
      TAILSCALE_AUTHKEY: "${TAILSCALE_AUTHKEY:-}"
      MINIO_ENDPOINT: "${MINIO_ENDPOINT:-http://minio:9000}"
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY:-minioadmin}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY:-minioadmin}"
      WEAVIATE_ENDPOINT: "${WEAVIATE_ENDPOINT:-http://weaviate:8080}"
    network_mode: bridge
    restart: unless-stopped
