storage: /verdaccio/storage
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  "@cdaprod/*":
    access: $all
    publish: $all
    proxy: npmjs
  "**":
    access: $all
    publish: $authenticated
    proxy: npmjs
security:
  api:
    legacy: true
middlewares: {}
logs: { type: stdout, format: pretty, level: http }
listen: 0.0.0.0:4873
