services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: thatdamtoolbox-keycloak
    networks: [damnet]
    ports: ["8089:8080"]
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    # Guard: only run when provider=keycloak (otherwise exit fast/no-op)
    command: ["sh","-lc","[ \"$${OIDC_PROVIDER:-auth0}\" = keycloak ] || { echo 'Keycloak disabled'; exit 0; }; exec /opt/keycloak/bin/kc.sh start-dev --import-realm"]
    volumes:
      - ../../seeds/keycloak:/opt/keycloak/data/import:ro
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    profiles: ["keycloak"]

networks:
  damnet:
    external: true
