x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "5"

x-build-common: &build-common
  args:
    BUILDKIT_INLINE_CACHE: "1"
  cache_from:
    - type=registry,ref=ghcr.io/cdaprod/thatdamtoolbox-cache:build
    - type=local,src=${BUILDX_CACHE_SRC:-$HOME/.cache/buildx-cache}
  cache_to:
    - type=local,dest=${BUILDX_CACHE_DEST:-$HOME/.cache/buildx-cache},mode=max,sharing=locked
  labels:
    org.opencontainers.image.source: "https://github.com/Cdaprod/Media-Indexer-Stdlib-Prototype"
    org.opencontainers.image.vendor: "Cdaprod"
    org.opencontainers.image.title: "ThatDAMToolbox"
    org.opencontainers.image.revision: "${GIT_SHA:-dev}"
    org.opencontainers.image.version: "${IMAGE_TAG:-dev}"
    org.opencontainers.image.licenses: "Apache-2.0"

services:
  supervisor:
    build:
      <<: *build-common
      context: ../../
      dockerfile: host/services/supervisor/Dockerfile
    image: cdaprod/supervisor:${IMAGE_TAG:-dev}
    container_name: thatdamtoolbox-supervisor
    networks: [damnet]
    ports: ["8070:8070"]
    logging: *default-logging
    environment:
      SUPERVISOR_API_KEY: "changeme"
      EVENT_BROKER_URL: "amqp://video:video@rabbitmq:5672/"
      EVENT_PREFIX: "overlay"
      BUS_KIND: "amqp"
      BROKER_URL: "amqp://video:video@rabbitmq:5672/"
      BROKER_EXCHANGE: "events"
      BROKER_QUEUE: "supervisor"
      BROKER_KIND: "direct"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8070/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    depends_on:
      - rabbitmq
    restart: unless-stopped
