services:
  # ────────────────────────────────────────────────────────────────────────────
  # A) DEFAULT: SAFE DISCOVERY (no docker.sock, no privileged)
  # ────────────────────────────────────────────────────────────────────────────
  thatdamtoolbox-discovery:
    build:
      <<: *build-common
      # NOTE: this file lives in /docker/compose/, so repo root is ../../
      context: ../../
      dockerfile: host/services/discovery/Dockerfile
    logging: *default-logging
    image: cdaprod/thatdam-discovery:${IMAGE_TAG:-dev}
    container_name: thatdamtoolbox-discovery

    # Discovery binds a tiny HTTP port on the host for health & leader file
    network_mode: host
    restart: unless-stopped

    environment:
      ROLE: agent
      UPSTREAM_HOST: api-gateway
      UPSTREAM_PORT: "8080"

      # auto => mDNS on LAN by default; can be forced to mdns|serf explicitly
      DISCOVERY_BACKEND: ${DISCOVERY_BACKEND:-auto}     # auto|mdns|serf

      # Service identity advertised to peers
      SERVICE_NAME: ${SERVICE_NAME:-thatdam}
      SERVICE_PORT: ${SERVICE_PORT:-8080}

      # Local probe / health surface (HTTP)
      DISCOVERY_HTTP_PORT: ${DISCOVERY_HTTP_PORT:-9999}

      # Leader election artifact written for other containers to read
      LEADER_FILE: ${LEADER_FILE:-/run/discovery/leader.env}

      # logging: text|json
      LOG_FORMAT: text

      # Orchestrator disabled by default (no docker.sock mount)
      DISCOVERY_ORCHESTRATE: "false"

    volumes:
      # Shared tmpfs/host bind provided by root compose (do not redefine here)
      - discovery-run:/run/discovery

    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:9999/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # ────────────────────────────────────────────────────────────────────────────
  # B) OPTIONAL: ORCHESTRATOR PROFILE (off by default)
  #     - Enables scheduling/placement duties on this host
  #     - Requires docker.sock to manage containers
  #     - Activate with:  docker compose --profile orchestrator up -d
  # ────────────────────────────────────────────────────────────────────────────
  thatdamtoolbox-discovery-orchestrator:
    extends:
      service: thatdamtoolbox-discovery
    container_name: thatdamtoolbox-discovery-orchestrator
    profiles: ["orchestrator"]

    environment:
      DISCOVERY_ORCHESTRATE: "true"
      LOG_FORMAT: text

    volumes:
      - discovery-run:/run/discovery
      # Grants container-control when orchestrator mode is enabled
      - /var/run/docker.sock:/var/run/docker.sock:rw
