x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "5"

x-build-common: &build-common
  args:
    BUILDKIT_INLINE_CACHE: "1"
  cache_from:
    - type=local,src=/tmp/buildx-cache
  cache_to:
    - type=local,dest=/tmp/buildx-cache,mode=max
  labels:
    org.opencontainers.image.source: "https://github.com/Cdaprod/Media-Indexer-Stdlib-Prototype"
    org.opencontainers.image.vendor: "Cdaprod"
    org.opencontainers.image.title: "ThatDAMToolbox"
    org.opencontainers.image.revision: "${GIT_SHA:-dev}"
    org.opencontainers.image.version: "${IMAGE_TAG:-dev}"
    org.opencontainers.image.licenses: "Apache-2.0"

services:
  gateway:
    build:
      <<: *build-common
      context: ../../docker/nginx
      dockerfile: Dockerfile
    image: cdaprod/gateway:latest
    container_name: thatdamtoolbox-gateway
    entrypoint: ["/bin/bash","-lc",". /opt/shared/entrypoint-snippet.sh && exec /entrypoint.sh"]
    networks: [damnet]
    ports: ["80:80"]
    restart: unless-stopped
    depends_on:
      - api-gateway
      - video-web
      - video-api
      - thatdamtoolbox-discovery
    environment:
      UPSTREAM_HOST: api-gateway
      UPSTREAM_PORT: "8080"
      UPSTREAM: api-gateway:8080
      SERVICE_PORT: "8080"
    volumes:
      - ../../host/services/shared/entrypoint-snippet.sh:/opt/shared/entrypoint-snippet.sh:ro
      - ../../docker/nginx/entrypoint.sh:/entrypoint.sh:ro
      - ../../docker/nginx/templates:/etc/nginx/templates:ro
      - ../../docker/web-app/build:/usr/share/nginx/html:ro
    healthcheck:
      test: ["CMD","curl","-fsS","http://127.0.0.1/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    logging: *default-logging
