name: thatdamtoolbox-server
services:
  overlay-hub:
    image: cdaprod/overlay-hub:${IMAGE_TAG:-dev}
    container_name: thatdamtoolbox-overlay-hub
    restart: unless-stopped
    depends_on: {}
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8090/healthz"]
      interval: 5s
      timeout: 2s
      retries: 12
      start_period: 10s

  capture-daemon:
    image: cdaprod/video-capture-daemon:${IMAGE_TAG:-dev}
    container_name: thatdamtoolbox-capture-daemon
    restart: unless-stopped
    depends_on:
      - rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:9000/devices"]
      interval: 5s
      timeout: 2s
      retries: 12
      start_period: 10s

  video-api:
    image: cdaprod/video:${IMAGE_TAG:-dev}
    container_name: thatdamtoolbox-video-api
    restart: unless-stopped
    env_file: [ .env ]
    ports: [ "8080:8080" ]
    volumes:
      - ./data:/data
    depends_on:
      - rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8080/health"]
      interval: 5s
      timeout: 2s
      retries: 12
      start_period: 10s

  api-gateway:
    image: cdaprod/api-gateway:${IMAGE_TAG:-dev}
    container_name: thatdamtoolbox-api-gateway
    restart: unless-stopped
    env_file: [ .env ]
    ports: [ "8081:8081" ]
    depends_on:
      - video-api
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8081/__health"]
      interval: 5s
      timeout: 2s
      retries: 12
      start_period: 10s

  video-web:
    image: cdaprod/video-web:${IMAGE_TAG:-dev}
    container_name: thatdamtoolbox-video-web-app
    restart: unless-stopped
    env_file: [ .env ]
    ports: [ "3000:3000" ]
