version: "3.9"
services:
  thatdamtoolbox-discovery:
    build:
      context: .
      dockerfile: host/services/discovery/Dockerfile
    image: cdaprod/thatdam-discovery:latest
    container_name: thatdamtoolbox-discovery
    network_mode: host
    restart: unless-stopped
    environment:
      DISCOVERY_BACKEND: ${DISCOVERY_BACKEND:-auto}
      SERVICE_NAME: ${SERVICE_NAME:-thatdam}
      SERVICE_PORT: ${SERVICE_PORT:-8080}
      DISCOVERY_HTTP_PORT: ${DISCOVERY_HTTP_PORT:-9999}
      LEADER_FILE: ${LEADER_FILE:-/run/discovery/leader.env}
    volumes:
      - thatdamtoolbox_discovery-run:/run/discovery
    healthcheck:
      test: ["CMD","curl","-fsS","http://127.0.0.1:9999/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  thatdamtoolbox_discovery-run:
    external: true

