services:
  media-api:
    profiles: ["media-api"]
    build:
      context: ../../
      dockerfile: host/services/media-api/Dockerfile
    image: cdaprod/media-api:${IMAGE_TAG:-dev}
    container_name: thatdamtoolbox-media-api
    networks: [damnet]
    ports: ["8081:8080"]
    environment:
      EVENT_BROKER_URL: "amqp://video:video@rabbitmq:5672/"
    depends_on:
      - rabbitmq
