x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "5"

x-build-common: &build-common
  args:
    BUILDKIT_INLINE_CACHE: "1"
  cache_from:
    - type=local,src=/tmp/buildx-cache
  labels:
    org.opencontainers.image.source: "https://github.com/Cdaprod/Media-Indexer-Stdlib-Prototype"
    org.opencontainers.image.vendor: "Cdaprod"
    org.opencontainers.image.title: "ThatDAMToolbox"
    org.opencontainers.image.revision: "${GIT_SHA:-dev}"
    org.opencontainers.image.version: "${IMAGE_TAG:-dev}"
    org.opencontainers.image.licenses: "Apache-2.0"

services:
  rabbitmq:
    build:
      <<: *build-common
      context: ../../docker/rabbitmq
      dockerfile: Dockerfile
    image: cdaprod/thatdamtoolbox-rabbitmq:${IMAGE_TAG:-dev}
    container_name: thatdamtoolbox-rabbitmq
    restart: unless-stopped
    networks: [damnet]
    hostname: rabbitmq
    entrypoint: ["/usr/local/bin/rabbitmq-entrypoint.sh"]
    environment:
      RABBITMQ_DEFAULT_USER: video
      RABBITMQ_DEFAULT_PASS: video
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_DISK_FREE_LIMIT: 50MB
      RABBITMQ_FEATURE_FLAGS: classic_mirrored_queue_version
    ports: ["5672:5672", "15672:15672"]
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging: *default-logging
