name: thatdamtoolbox-server
services:
  api-gateway:
    image: ${GHCR_IMAGE_PREFIX}/api-gateway:${IMAGE_TAG}
    restart: unless-stopped
    env_file: [ .env ]
    ports: [ "8081:8081" ]
    depends_on: [ video-api, video-web ]
  video-api:
    image: ${GHCR_IMAGE_PREFIX}/video-api:${IMAGE_TAG}
    restart: unless-stopped
    env_file: [ .env ]
    ports: [ "8080:8080" ]
    volumes:
      - ./data:/data
  video-web:
    image: ${GHCR_IMAGE_PREFIX}/video-web:${IMAGE_TAG}
    restart: unless-stopped
    env_file: [ .env ]
    ports: [ "3000:3000" ]
