x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "5"

x-build-common: &build-common
  args:
    BUILDKIT_INLINE_CACHE: "1"
  cache_from:
    - type=local,src=${BUILDX_CACHE_SRC:-$HOME/.cache/buildx-cache}
  cache_to:
    - type=local,dest=${BUILDX_CACHE_DEST:-$HOME/.cache/buildx-cache},mode=max
  labels:
    org.opencontainers.image.source: "https://github.com/Cdaprod/Media-Indexer-Stdlib-Prototype"
    org.opencontainers.image.vendor: "Cdaprod"
    org.opencontainers.image.title: "ThatDAMToolbox"
    org.opencontainers.image.revision: "${GIT_SHA:-dev}"
    org.opencontainers.image.version: "${IMAGE_TAG:-dev}"
    org.opencontainers.image.licenses: "Apache-2.0"

services:
  minio:
    build:
      <<: *build-common
      context: ../../docker/minio
      dockerfile: Dockerfile
    image: thatdamtoolbox-minio:local
    container_name: thatdamtoolbox-minio
    environment:
      MINIO_ROOT_USER:     minio
      MINIO_ROOT_PASSWORD: minio123

      # Buckets to bootstrap
      MINIO_BUCKET_MEDIA: "media"
      MINIO_BUCKET_WEAVIATE_BACKUPS: "weaviate-backups"

      # Make media bucket publicly readable (optional)
      MINIO_MEDIA_PUBLIC: "true"

      # Optional CORS for media bucket (single-line JSON)
      # MINIO_MEDIA_CORS_JSON: >-
      #   [{"AllowedMethods":["GET","HEAD"],
      #     "AllowedOrigins":["*"],
      #     "AllowedHeaders":["*"],
      #     "ExposeHeaders":["ETag"],
      #     "MaxAgeSeconds":300}]

      # Webhook (kept from your previous setup)
      MINIO_NOTIFY_WEBHOOK_ENABLE_primary: "on"
      MINIO_NOTIFY_WEBHOOK_ENDPOINT_primary: "http://webhook:5000/events"
      MINIO_NOTIFY_WEBHOOK_AUTH_TOKEN_primary: ""
      MINIO_SVC_ACCESS_KEY:  thatdam_app
      MINIO_SVC_SECRET_KEY:  thatdam_app_secret
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ../../docker/minio/data:/data
    # ✅ mc-based healthcheck: no curl/wget required
    healthcheck:
      test: ["CMD-SHELL", "mc alias set hc http://localhost:9000 \"$$MINIO_ROOT_USER\" \"$$MINIO_ROOT_PASSWORD\" >/dev/null 2>&1 || true; mc admin info hc >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 40s
    restart: unless-stopped
    networks: [damnet]
    logging: *default-logging