x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "5"

x-build-common: &build-common
  args:
    BUILDKIT_INLINE_CACHE: "1"
  cache_from:
    - type=registry,ref=ghcr.io/cdaprod/thatdamtoolbox-cache:build,ignore-error=true
  labels:
    org.opencontainers.image.source: "https://github.com/Cdaprod/Media-Indexer-Stdlib-Prototype"
    org.opencontainers.image.vendor: "Cdaprod"
    org.opencontainers.image.title: "ThatDAMToolbox"
    org.opencontainers.image.revision: "${GIT_SHA:-dev}"
    org.opencontainers.image.version: "${IMAGE_TAG:-dev}"
    org.opencontainers.image.licenses: "Apache-2.0"

services:
  media-api:
    profiles: ["media-api"]
    build:
      <<: *build-common
      context: ../../
      dockerfile: host/services/media-api/Dockerfile
    image: ghcr.io/cdaprod/media-api:${IMAGE_TAG:-dev}
    container_name: thatdamtoolbox-media-api
    networks: [damnet]
    ports: ["8081:8080"]
    logging: *default-logging
    environment:
      EVENT_BROKER_URL: "amqp://video:video@rabbitmq:5672/"
      BLOB_STORE_ROOT: /data
    volumes:
      - "${DATA_ROOT:-./data}:/data:rw"
      - "${INCOMING_ROOT:-./incoming}:/data/_INCOMING:rw"
    depends_on:
      - rabbitmq
