x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "5"

x-build-common: &build-common
  args:
    BUILDKIT_INLINE_CACHE: "1"
  cache_from:
    - type=local,src=/tmp/buildx-cache
  cache_to:
    - type=local,dest=/tmp/buildx-cache,mode=max
  labels:
    org.opencontainers.image.source: "https://github.com/Cdaprod/Media-Indexer-Stdlib-Prototype"
    org.opencontainers.image.vendor: "Cdaprod"
    org.opencontainers.image.title: "ThatDAMToolbox"
    org.opencontainers.image.revision: "${GIT_SHA:-dev}"
    org.opencontainers.image.version: "${IMAGE_TAG:-dev}"
    org.opencontainers.image.licenses: "Apache-2.0"

services:
  auth-bridge:
    build:
      <<: *build-common
      context: ../../
      dockerfile: docker/auth-bridge/Dockerfile
    image: cdaprod/auth-bridge:${IMAGE_TAG:-dev}
    # (optional) avoid container_name clash with keycloak variant
    container_name: thatdamtoolbox-auth-auth0
    networks:
      damnet:
        aliases: ["auth-bridge"]
    ports: ["8081:8081"]
    logging: *default-logging
    environment:
      OIDC_PROVIDER: "auth0"
      OIDC_ISSUER: "${AUTH0_ISSUER:-https://example.us.auth0.com/}"
      OIDC_CLIENT_ID: "${AUTH0_CLIENT_ID:-changeme}"
      OIDC_CLIENT_SECRET: "${AUTH0_CLIENT_SECRET:-changeme}"
      OIDC_SCOPES: "openid profile email"
      AUTH_REDIRECT_BASE: "${AUTH_REDIRECT_BASE:-http://localhost:8081}"
      AUTH_COOKIE_DOMAIN: "${AUTH_COOKIE_DOMAIN:-localhost}"
      AUTH_ALLOWED_ORIGINS: "${AUTH_ALLOWED_ORIGINS:-http://localhost:3000}"
      TENANCY_URL: "${TENANCY_URL:-http://tenancy:8082}"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8081/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    profiles: ["auth0"]
