x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "5"

x-build-common: &build-common
  args:
    BUILDKIT_INLINE_CACHE: "1"
  cache_from:
    - type=registry,ref=ghcr.io/cdaprod/thatdamtoolbox-cache:build
    - type=local,src=${BUILDX_CACHE_SRC:-$HOME/.cache/buildx-cache}
  cache_to:
    - type=local,dest=${BUILDX_CACHE_DEST:-$HOME/.cache/buildx-cache},mode=max
  labels:
    org.opencontainers.image.source: "https://github.com/Cdaprod/Media-Indexer-Stdlib-Prototype"
    org.opencontainers.image.vendor: "Cdaprod"
    org.opencontainers.image.title: "ThatDAMToolbox"
    org.opencontainers.image.revision: "${GIT_SHA:-dev}"
    org.opencontainers.image.version: "${IMAGE_TAG:-dev}"
    org.opencontainers.image.licenses: "Apache-2.0"

services:
  api-gateway:
    build:
      <<: *build-common
      context: ../../
      dockerfile: host/services/api-gateway/Dockerfile
    image: cdaprod/api-gateway:${IMAGE_TAG:-dev}
    container_name: thatdamtoolbox-api-gateway
    networks: [damnet]
    ports: ["8085:8080"]
    logging: *default-logging
    environment:
      EVENT_BROKER_URL: "amqp://video:video@rabbitmq:5672/"
      NEXT_PUBLIC_LOGIN_URL: "https://idp.example.com/login"
      NEXT_PUBLIC_PLAUSIBLE_DOMAIN: "example.com"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - rabbitmq
    restart: unless-stopped
