x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "5"

x-build-common: &build-common
  args:
    BUILDKIT_INLINE_CACHE: "1"
  cache_from:
    - type=local,src=/tmp/buildx-cache
  cache_to:
    - type=local,dest=/tmp/buildx-cache,mode=max
  labels:
    org.opencontainers.image.source: "https://github.com/Cdaprod/Media-Indexer-Stdlib-Prototype"
    org.opencontainers.image.vendor: "Cdaprod"
    org.opencontainers.image.title: "ThatDAMToolbox"
    org.opencontainers.image.revision: "${GIT_SHA:-dev}"
    org.opencontainers.image.version: "${IMAGE_TAG:-dev}"
    org.opencontainers.image.licenses: "Apache-2.0"

services:
  runner:
    build:
      <<: *build-common
      context: ../../
      dockerfile: host/services/runner/Dockerfile
    image: cdaprod/runner:${IMAGE_TAG:-dev}
    container_name: thatdamtoolbox-runner
    networks: [damnet]
    logging: *default-logging
    environment:
      SUPERVISOR_URL: "http://supervisor:8070"
    depends_on:
      - supervisor
    healthcheck:
      test: ["CMD", "sh", "-c", "pgrep runner >/dev/null"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped
