x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "5"

x-build-common: &build-common
  args:
    BUILDKIT_INLINE_CACHE: "1"
  cache_from:
    - type=local,src=/tmp/buildx-cache
  cache_to:
    - type=local,dest=/tmp/buildx-cache,mode=max
  labels:
    org.opencontainers.image.source: "https://github.com/Cdaprod/Media-Indexer-Stdlib-Prototype"
    org.opencontainers.image.vendor: "Cdaprod"
    org.opencontainers.image.title: "ThatDAMToolbox"
    org.opencontainers.image.revision: "${GIT_SHA:-dev}"
    org.opencontainers.image.version: "${IMAGE_TAG:-dev}"
    org.opencontainers.image.licenses: "Apache-2.0"

services:
  camera-proxy:
    build:
      <<: *build-common
      context: ../../
      dockerfile: host/services/camera-proxy/Dockerfile
    image: cdaprod/camera-proxy:${IMAGE_TAG:-dev}
    container_name: thatdamtoolbox-camera-proxy
    networks: [damnet]
    ports: ["8000:8000"]
    entrypoint: ["/entrypoint.sh"]
    volumes:
      - ../../host/services/shared/entrypoint-snippet.sh:/opt/shared/entrypoint-snippet.sh:ro
      - ../../host/services/camera-proxy/entrypoint.sh:/entrypoint.sh:ro
      - discovery-run:/run/discovery:ro
      - /dev:/dev:rw,rshared
    device_cgroup_rules:
      - "c 81:* rmw"
      - "c 226:* rmw"
    group_add: ["video"]
    environment:
      EVENT_BROKER_URL: "${EVENT_BROKER_URL:-amqp://video:video@rabbitmq:5672/}"
      NEXT_PUBLIC_LOGIN_URL: "${NEXT_PUBLIC_LOGIN_URL:-https://idp.example.com/login}"
      NEXT_PUBLIC_PLAUSIBLE_DOMAIN: "${NEXT_PUBLIC_PLAUSIBLE_DOMAIN:-example.com}"
      OVERLAY_HUB_URL: "${OVERLAY_HUB_URL:-http://overlay-hub:8090}"
      CAPTURE_DAEMON_URL: "${CAPTURE_DAEMON_URL:-http://capture-daemon:9000}"
      CAPTURE_DAEMON_TOKEN: "${CAPTURE_DAEMON_TOKEN:-devtoken}"
      ICE_SERVERS: "${ICE_SERVERS:-stun:stun.l.google.com:19302}"
      FFMPEG_HWACCEL: "${FFMPEG_HWACCEL:-}"
      UPSTREAM_HOST: "${UPSTREAM_HOST:-api-gateway}"
      UPSTREAM_PORT: "${UPSTREAM_PORT:-8080}"
    logging: *default-logging
    healthcheck:
      test: ["CMD","curl","-fsS","http://127.0.0.1:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - overlay-hub
      - thatdamtoolbox-discovery
