services:
  media-api:
    profiles: ["media-api"]
    build:
      <<: *build-common
      context: ../../
      dockerfile: host/services/media-api/Dockerfile
    image: cdaprod/media-api:${IMAGE_TAG:-dev}
    container_name: thatdamtoolbox-media-api
    networks: [damnet]
    ports: ["8081:8080"]
    logging: *default-logging
    environment:
      EVENT_BROKER_URL: "amqp://video:video@rabbitmq:5672/"
      BLOB_STORE_ROOT: /data
    volumes:
      - "${DATA_ROOT:-./data}:/data:rw"
      - "${INCOMING_ROOT:-./incoming}:/data/_INCOMING:rw"
    depends_on:
      - rabbitmq
