x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "5"

x-build-common: &build-common
  args:
    BUILDKIT_INLINE_CACHE: "1"
  cache_from:
    - type=registry,ref=ghcr.io/cdaprod/thatdamtoolbox-cache:build
    - type=local,src=${BUILDX_CACHE_SRC:-$HOME/.cache/buildx-cache}
  cache_to:
    - type=local,dest=${BUILDX_CACHE_DEST:-$HOME/.cache/buildx-cache},mode=max,sharing=locked
  labels:
    org.opencontainers.image.source: "https://github.com/Cdaprod/Media-Indexer-Stdlib-Prototype"
    org.opencontainers.image.vendor: "Cdaprod"
    org.opencontainers.image.title: "ThatDAMToolbox"
    org.opencontainers.image.revision: "${GIT_SHA:-dev}"
    org.opencontainers.image.version: "${IMAGE_TAG:-dev}"
    org.opencontainers.image.licenses: "Apache-2.0"

services:
  overlay-hub:
    build:
      <<: *build-common
      context: ../../
      dockerfile: host/services/overlay-hub/Dockerfile
    image: cdaprod/overlay-hub:${IMAGE_TAG:-dev}
    container_name: thatdamtoolbox-overlay-hub
    networks: [damnet]
    ports: ["8090:8090"]
    logging: *default-logging
    environment:
      JWKS_URL: "http://api-gateway:8080/.well-known/jwks.json"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8090/healthz"]
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo "waiting for JWKS at http://api-gateway:8080/.well-known/jwks.json"
        until wget -qO- http://api-gateway:8080/.well-known/jwks.json >/dev/null 2>&1; do
          sleep 2
        done
        exec /app/overlay-hub
    depends_on:
      - api-gateway
    restart: unless-stopped
