# local anchors live in THIS file (anchors don't cross includes)
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "5"

x-build-common: &build-common
  args:
    BUILDKIT_INLINE_CACHE: "1"
  cache_from:
    - type=registry,ref=ghcr.io/cdaprod/thatdamtoolbox-cache:build,ignore-error=true
  labels:
    org.opencontainers.image.source: "https://github.com/Cdaprod/Media-Indexer-Stdlib-Prototype"
    org.opencontainers.image.vendor: "Cdaprod"
    org.opencontainers.image.title: "ThatDAMToolbox"
    org.opencontainers.image.revision: "${GIT_SHA:-dev}"
    org.opencontainers.image.version: "${IMAGE_TAG:-dev}"
    org.opencontainers.image.licenses: "Apache-2.0"

services:
  web-site:
    build:
      <<: *build-common
      context: ../../docker/web-site
      dockerfile: Dockerfile
      target: development
    logging: *default-logging
    image: cdaprod/web-site:${IMAGE_TAG:-dev}
    container_name: thatdamtoolbox-web-site
    platform: linux/arm64
    ports: ["3001:3000"]
    networks: [damnet]
    profiles: [web-site]
    environment:
      NODE_ENV: development
      NPM_CONFIG_CACHE: /root/.npm
      EVENT_BROKER_URL: "amqp://video:video@rabbitmq:5672/"
      NEXT_PUBLIC_LOGIN_URL: "https://idp.example.com/login"
      NEXT_PUBLIC_PLAUSIBLE_DOMAIN: "example.com"
      
      # You can also override here in CI or host:
      # SENDGRID_API_KEY: ${SENDGRID_API_KEY}
    volumes:
      - ../../docker/web-site:/app:cached
      - web-site-node_modules:/app/node_modules
      - web-site-next:/app/.next
      - web-site-npm:/root/.npm
    entrypoint: ["/bin/sh","-c","chmod +x /app/entrypoint.sh && /app/entrypoint.sh"]
    depends_on:
      - rabbitmq
    restart: unless-stopped
    mem_limit: 256m
    cpus: 0.25
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
