services:
  minio:
    build:
      context: ../../
      dockerfile: docker/minio/Dockerfile
    image: thatdamtoolbox-minio:local
    container_name: thatdamtoolbox-minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_BUCKET_MEDIA: "media"
      MINIO_BUCKET_WEAVIATE_BACKUPS: "weaviate-backups"
      MINIO_MEDIA_PUBLIC: "true"
      MINIO_NOTIFY_WEBHOOK_ENABLE_primary: "on"
      MINIO_NOTIFY_WEBHOOK_ENDPOINT_primary: "http://webhook:5000/events"
      MINIO_NOTIFY_WEBHOOK_AUTH_TOKEN_primary: ""
      MINIO_SVC_ACCESS_KEY: thatdam_app
      MINIO_SVC_SECRET_KEY: thatdam_app_secret
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ../../docker/minio/data:/data
    healthcheck:
      test: ["CMD","curl","-fsS","http://localhost:9000/minio/health/ready"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    networks: [damnet]
