# ──────────────────────────────────────────────────────────────
# Weaviate vector-DB
# ──────────────────────────────────────────────────────────────
services:
  weaviate:
    image: semitechnologies/weaviate:latest
    container_name: thatdamtoolbox-weaviate
    command: ["--host","0.0.0.0","--port","8080","--scheme","http"]
    ports: ["8082:8080","50051:50051"]
    environment:
      QUERY_DEFAULTS_LIMIT:                 25
      DEFAULT_VECTORIZER_MODULE:            'none'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH:                /var/lib/weaviate
      ENABLE_MODULES:                       backup-s3
      BACKUP_S3_BUCKET:                     weaviate-backups
      BACKUP_S3_ENDPOINT:                   http://minio:9000
      BACKUP_S3_ACCESS_KEY_ID:              minio
      BACKUP_S3_SECRET_ACCESS_KEY:          minio123
      BACKUP_S3_USE_SSL:                    'false'
      CLUSTER_HOSTNAME:                     node1
      POSTGRES_HOST:                        postgres
      POSTGRES_PASSWORD:                    weaviate
      POSTGRES_USER:                        weaviate
      POSTGRES_DB:                          weaviate
    volumes: ["./data/weaviate:/var/lib/weaviate"]
    depends_on:
      - minio
      - postgres
