version: "3.9"
name: thatdamtoolbox-web-site

services:
  web-site:
    build:
      context: ../web-site          # NOTE: relative to this compose file's folder
      dockerfile: Dockerfile
      # target: production          # final stage is production by default
    image: ghcr.io/cdaprod/thatdamtoolbox-website:latest
    container_name: thatdamtoolbox-website
    restart: unless-stopped
    env_file:
      - ../web-site/.env            # keep secrets/env outside image
    environment:
      NODE_ENV: production
    ports: ["3000:3000"]
    networks: [damnet]

networks:
  damnet:
    external: true