# docker/traefik/Dockerfile
# Traefik reverse proxy with OCI labels for That DAM Toolbox.
# Usage:
#   docker build -t cdaprod/traefik:dev docker/traefik
# Accepts VERSION and GIT_SHA build args for labeling.
FROM traefik:v3.1
